#ifndef LOW_LEVEL_PROGRAMMING_TASK1_STRING_CRUD_H
#define LOW_LEVEL_PROGRAMMING_TASK1_STRING_CRUD_H

#include "crud_util.h"

DECLARE_INSERT_FUNCTION(String, string)
DECLARE_RETRIEVE_FUNCTION(String, string)

#endif //LOW_LEVEL_PROGRAMMING_TASK1_STRING_CRUD_H
