#ifndef LOW_LEVEL_PROGRAMMING_TASK1_COMPARATION_H
#define LOW_LEVEL_PROGRAMMING_TASK1_COMPARATION_H

typedef enum {
    CMP_LESS,
    CMP_EQUAL,
    CMP_GREATER,
    CMP_UNDEFINED
} Comparation, CMP;

#endif //LOW_LEVEL_PROGRAMMING_TASK1_COMPARATION_H
